'use client';

import { useState } from 'react';
import { Copy, Check } from 'lucide-react';
import { GeneratedMemo } from '@/lib/types';
import MemoSection from './MemoSection';

interface Props {
  memo: GeneratedMemo;
  onRegenerateSection: (sectionTitle: string) => void;
}

export default function MemoDocument({ memo, onRegenerateSection }: Props) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    const text = [
      `# ${memo.dealTitle}`,
      `${memo.subtitle}`,
      `Prepared ${new Date(memo.generatedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
      '',
      ...memo.sections.map((s) => `## ${s.number}. ${s.title}\n\n${s.content}`),
    ].join('\n\n');

    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const dateStr = new Date(memo.generatedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <div className="animate-fade-in" style={{ width: '100%', maxWidth: '720px', margin: '0 auto' }}>
      <div
        style={{
          backgroundColor: '#F8F9FA',
          borderTop: '3px solid var(--accent)',
          borderRadius: '8px',
          boxShadow: '0 4px 24px rgba(0, 0, 0, 0.4), 0 1px 4px rgba(0, 0, 0, 0.2)',
          padding: '40px 48px',
        }}
      >
        {/* Document header */}
        <div style={{ marginBottom: '32px', paddingBottom: '24px', borderBottom: '1px solid #e2e8f0' }}>
          <div
            style={{
              display: 'inline-block',
              fontSize: '0.6875rem',
              fontWeight: '600',
              letterSpacing: '0.12em',
              textTransform: 'uppercase',
              color: '#dc2626',
              backgroundColor: '#fef2f2',
              border: '1px solid #fecaca',
              borderRadius: '4px',
              padding: '2px 8px',
              marginBottom: '16px',
            }}
          >
            Confidential
          </div>

          <h1
            style={{
              fontFamily: "'Instrument Serif', Georgia, serif",
              fontSize: '2rem',
              lineHeight: '1.2',
              color: '#0f172a',
              marginBottom: '8px',
              letterSpacing: '-0.01em',
            }}
          >
            {memo.dealTitle}
          </h1>

          <p style={{ fontSize: '0.9375rem', color: '#475569', marginBottom: '6px' }}>
            {memo.dealType} — Investment Memo
          </p>

          <p style={{ fontSize: '0.8125rem', color: '#94a3b8' }}>Prepared {dateStr}</p>
        </div>

        {/* Sections */}
        <div>
          {memo.sections.map((section, i) => (
            <MemoSection
              key={section.id}
              section={section}
              onRegenerate={onRegenerateSection}
              animationDelay={i * 100}
            />
          ))}
        </div>

        {/* Footer */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingTop: '24px',
            borderTop: '1px solid #e2e8f0',
            marginTop: '8px',
          }}
        >
          <p style={{ fontSize: '0.75rem', color: '#9ca3af', maxWidth: '400px', lineHeight: '1.5' }}>
            Generated by DealDraft. This memo is AI-generated for demonstration purposes only and does not constitute financial or investment advice.
          </p>

          <button
            onClick={handleCopy}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              padding: '7px 14px',
              borderRadius: '6px',
              border: '1px solid #e2e8f0',
              backgroundColor: copied ? '#f0fdf4' : 'white',
              cursor: 'pointer',
              fontSize: '0.8125rem',
              color: copied ? '#16a34a' : '#374151',
              fontWeight: '500',
              whiteSpace: 'nowrap',
              flexShrink: 0,
              marginLeft: '16px',
            }}
          >
            {copied ? <Check size={14} /> : <Copy size={14} />}
            {copied ? 'Copied ✓' : 'Copy Memo'}
          </button>
        </div>
      </div>
    </div>
  );
}
